config/routes.rb
Learnto::Application.routes.draw do

  get "networks/show"
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get 'auth/:provider/callback' => 'sessions#create', :as => "social_sign_in"
  get 'auth/failure' => redirect('/')

  get "healthbox" => "networks#show", defaults: {id: 5}
  get "bgsa" => "networks#show", defaults: {id: 2}
  get "startlabs" => "networks#show", defaults: {id: 3}
  get "startiap" => "networks#show", defaults: {id: 7}
  get "gsd" => "networks#show", defaults: {id: 8}
  get "cic" => "networks#show", defaults: {id: 9}
  get "sase" => "networks#show", defaults: {id: 10}

  get "about" => 'static_pages#about', :as => "about"
  get "guidelines" => 'static_pages#guidelines', :as => "guidelines"
  get "team" => 'static_pages#team', :as => "team"
  get "whyteach" => 'static_pages#whyteach', :as => "whyteach"

  get "registration/register", as: 'register'
  patch "registration/update", as: 'update_registration'


  get '/' => 'networks#show', :constraints => { :subdomain => /^(?!www).+/ }

  root 'skills#index'

  get 'networks/:id' => 'networks#show'
  get 'networks/:id/join' => 'networks#join', as: 'join_network'

  resources :users do
    collection do
      # get "requests"
    end
  end

  resources :reviews do
    member do 
    end
  end

  resources :requests do
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :requests do
    member do
      get "add_user"
    end
  end

  get "networks/:id" => "networks#show", :as => "network"
  
  resources :events do
    member do 
      post 'attend'
    end
  end

  resources :skills do
    collection do
      get 'networks'
    end
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :lessons do
    member do
      get "approve"
      get "ignore"
      get "complete"
      get "add_student"
    end
  end

  resources :conversations do
    collection do
      get "inbox"
      post "reply"
    end
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :qualifications, presence: true
  validates :picture, presence: true

  belongs_to :user
  has_many :lessons

  has_many :networks, :through => :user
  has_many :reviews, :through => :lessons


  def hide
    self.hidden = true
    self.save!
  end

  def similar_skills
    if self.networks.size == 0
      return Skill.where("approved = ? AND hidden = ? AND public = ?", true, false, true).order("RANDOM()").first(3)
    else
      return self.networks.first.skills.where("approved = ? AND hidden = ?", true, false).order("RANDOM()").first(3)
    end
  end

  def openLessons
    lessons = []
    self.lessons.each do |lesson|
      if lesson.status == "APPROVED"
        lessons << lesson
      end
    end
    return lessons
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @show_banner = true
    @skills = Skill.where("approved = ? AND hidden = ? AND public = ?", true, false, true).order("RANDOM()")
    @events = Event.where("approved = ? AND public = ?", true, true).where("starts_at >= ?", DateTime.now).order("RANDOM()")
    @requests = Request.all
    @user = current_user

    if session[:new_user]
      @show_user_bio = true
      session.delete(:new_user)
    end

    respond_to do |format|
      format.html
      format.json {render json: custom_json_for(@skills)}
    end
  end

  def show
    @skill = Skill.find(params[:id])
    # @lesson = nil
    # if current_user
    #   @lesson = current_user.taken_class(@skill)
    #   if @lesson
    #     @review = current_user.reviewFor(@skill.user, @lesson)
    #   end
    # end
    # if !@review
    #   @review = Review.new
    # end

    if current_user and session[:show_modal] and session[:skill_id] == @skill.id
      @show_modal = true
      session.delete(:show_modal)
      session.delete(:skill_id)
    end

    if not current_user
      session[:show_modal] = true
      session[:skill_id] = @skill.id
    end

    if current_user
      @show_review_form = current_user.lessons.where(status:"COMPLETED").map(&:skill).include?(@skill) && !@skill.reviews.map(&:user).include?(current_user)
      if @show_review_form
        @review = Review.new
        @lesson = current_user.lessons.where(skill_id: @skill.id).first
      end
    end


    @reviews = @skill.reviews

    @completed_lessons = @skill.lessons.where(status: "COMPLETED").last(4)

    @return_to = request.path

    respond_to do |format|
      format.html
      format.json {render json: custom_json_for_single_skill(@skill)}
    end
  end

  def create
    @skill = current_user.skills.new(skill_params)

    if @skill.save
      Notifier.skill_added(@skill).deliver
      redirect_to @skill
    elsif @skill.errors.any?
      # break
      @skill.errors.full_messages.each do |msg|
        if !flash[:warning]
          flash[:warning] = msg + '. '
        else
          flash[:warning] += msg + '. '
        end
      end
      render 'new'
    else      
      render 'new'
    end
  end

  def new
    if not current_user
      redirect_to login_url(return_to: request.path)
      return
    end
    @skill = Skill.new
  end

  def edit
    @skill = current_user.skills.find(params[:id])
  end

  def remove
    @skill = current_user.skills.find(params[:id])
    @skill.hidden = true
    @skill.save!
    flash[:warning] = "Skill removed"
    redirect_to root_url
  end


  def update
    @skill = current_user.skills.find(params[:id])
    if @skill.update(skill_params)
      redirect_to @skill, notice: 'Skill was successfully updated.'
    else
      render 'edit'
    end
  end

  private
    def custom_json_for_single_skill(skill)
      value = 
      {
        teacher: skill.user.name,
        picture: skill.picture,
        description: skill.description,
        qualifications: skill.qualifications,
        reviews: skill.reviews,
        title: skill.title    
      }
      return value.to_json
    end

    def skill_params
      params.require(:skill).permit(:title, :description, :qualifications, :picture, :public)
    end

    def custom_json_for(value)
      list = value.map do |skill|
        {
          teacher: skill.user.name,
          picture: skill.picture,
          description: skill.description,
          qualifications: skill.qualifications,
          reviews: skill.reviews,
          title: skill.title
        }
      end
      return list.to_json
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_add_review.html.haml
.review
  .row
    .col-md-3
      .circle-overlay
        = image_tag user.picture
    .col-md-9
      .stargroup
        - for i in 0..4
          %i.glyphicon.glyphicon-star-empty.stars-unselected
      .body.message-text
        = form_for(review) do |f|
          .form-group
            = f.text_area :message, rows: 2, class: "form-control", placeholder: "Write your review here"
            = f.hidden_field :lesson_id, value: lesson.id
            = f.hidden_field :stars, value: 5
            = f.hidden_field :target_user_id, value: target_user.id
          = f.submit "Submit", class: "btn btn-custom"

app/views/skills/_form.html.haml
%h3
  Teach on LearnTo
%p
  Teaching is a great way to meet new people and learn from them! Here are 
  = link_to "three great reasons why you should teach today.", whyteach_path
%p
  If you're not sure what to teach, just think of something you love be it a sport, an instrument, or a technical skill.
%p
  Looking to teach a one time, scheduled lesson? Check out our #{link_to "scheduled lesson", new_event_path} form.
%hr.div-line
= form_for(@skill, {role: "form"}) do |f|
  .form-group
    = f.label :title, "Learn to..."
    %p.help-block
      Choose an interesting title to capture people's attention.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-question-sign
      = f.text_field :title, class: "form-control", placeholder: "i.e. 'Cook Italian food' or 'Build a website'"
  %hr.div-line
  .form-group
    = f.label :description
    %p.help-block
      Describe what you're going to help others learn.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-globe
      = f.text_area :description, rows: 5, class: "form-control", placeholder: "i.e. I can help you learn to make basic pastas, sauces, and pizzas! We can even work on making Italian deserts such as gelato!"
  %hr.div-line
  .form-group
    = f.label :qualifications
    %p.help-block
      Tell others why you're able to teach them.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-ok
      = f.text_area :qualifications, rows: 5, class: "form-control", placeholder: "i.e. I've been cooking for myself for many years and learned how to cook from my Italian mother. I absolutely love cooking (mainly because I like eating!) and would love to help someone pick it up."
  %hr.div-line
  .form-group
    = f.label :image
    %p.help-block
      Pick an image that describes your lesson.
    .upload-skill-picture.btn.btn-custom
      Upload an image that describes your skill
    %br
    = f.hidden_field :picture, class: "form-control"
  %hr.div-line
  .form-group
    = f.label :public
    = f.check_box :public, {checked: false}
    %p.help-block
      Public lessons are visible to anyone.  Private lessons are visible to only those in your network.
  %hr.div-line
    = f.submit "Submit", class: "btn btn-custom"

app/views/skills/_lesson_short.html.haml
- lesson_short.users.each do |user|
  .row
    %a.block{href: user_path(lesson_short.user)}
      .col-md-3
        .image.circle-overlay
          = image_tag user.picture
      .col-md-9
        .name
          = user.first_name

app/views/skills/_reference_short.html.haml
.reference
	.image.profile-pic
		=image_tag review_short.picture
  .message
    =review_short.message

app/views/skills/_request.html.haml
%a{:href => "#requestbox", :class=> 'btn btn-primary', :'data-toggle'=>'modal'} Request
#requestbox.modal.hide.fade
	.modal-content
		.modal-header
			%button{:type=>"button",:class=>"close", :'data-dismiss'=>"modal", :'aria-hidden'=>"true"}
			%h4{:class=> "modal=title"} Request Lesson - #{skill.title}
		.modal-body
			%p Tell #{skill.user.first_name} what you want to learn, why you want to learn it, and why you would be fun to teach!
			=form_tag send_request_path do
				=text_area_tag :request
				=hidden_field_tag :skill_id, skill.id
				=submit_tag 'Request', :class=>"btn btn-primary"
		.modal-footer
			%button{:type=>"button", :class=>"btn btn-default", :'data-dismiss'=>"modal"} Close

app/views/skills/_review_short.html.haml
.review
  .row
    .col-md-3
      %a.block{href: user_path(review_short.user)}
        .circle-overlay
          = image_tag review_short.user.picture
        .review-info
          .name
            = review_short.user.first_name
          .time
            = review_short.updated_at.strftime("%b-%d")
    .col-md-9
      -for i in 0..review_short.stars-1
        %i.glyphicon.glyphicon-star.stars
      .review-text
        = review_short.message

app/views/skills/_skill.html.haml
.skill
  .row
    .col-md-7
      .box
        - if @skill.approved == false
          .pending-approval
            Pending approval
        .row
          .col-md-12
            %h2.title
              = @skill.title
        .row
          .col-md-6
            %a{href: user_path(@skill.user), class: "circle-overlay"}
              = image_tag @skill.user.picture
            %h4.instructor
              = link_to @skill.user.name, user_path(@skill.user)
        .row
          .col-md-6
            .social-share
              .facebook
                .fb-share-button{"data-href" => "#{request.original_url}", "data-type" => "button_count"}
              .twitter
                %a.twitter-share-button{"data-via" => "comelearnto", href: "https://twitter.com/share"} Tweet
          %hr.div-line
        .action-links
          - if current_user == @skill.user
            = link_to 'Edit', edit_skill_path(id: @skill.id)
            = link_to 'Remove', remove_skill_path(@skill)
        %h4 Description
        .description
          = simple_format(@skill.description)
        .qualifications
          .qualifications-heading
            %h4 Qualifications
          .qualification-text
            = simple_format(@skill.qualifications)
        - if @skill.approved
          - if current_user
            %button.btn.btn-custom.contact{"data-target" => "#lessonModal", "data-toggle" => "modal"} Contact to find a time and place!
          - else
            = link_to "Sign up or log in", login_path(return_to: @return_to), class: "btn btn-custom contact"
          - if current_user != @skill.user
            .also-teach
              %p Think you can also teach this?  #{link_to 'Sign up to teach', new_skill_path}

      - if @reviews.length > 0 or @show_review_form
        .box
          %h3 Reviews
          - if @show_review_form
            .add-review
              = render partial: "add_review", locals: {lesson: @lesson, review: @review, user: current_user, target_user: @skill.user}
          .reviews
            = render partial: "review_short", collection: @reviews.reverse

    .col-md-5
      .skill-image-full
        = image_tag @skill.picture

      - unless @skill.similar_skills.empty?
        .box.recommendations
          %h4
            You might also like these lessons...
          %ul
            - @skill.similar_skills.each do |skill|
              %li
                = link_to skill.title, skill

      - if @completed_lessons && @completed_lessons.length > 0
        .box
          %h4 People who have learned with #{@skill.user.first_name}
          = render partial: "lesson_short", collection: @completed_lessons

      - if @skill.openLessons.size > 0
        .box
          %h4 Join a lesson that's about to happen
          - @skill.openLessons.each do |lesson|
            = link_to "Learn with " + lesson.users.first.first_name, lesson_url(lesson)
#lessonModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Sign up for the lesson! 
      = form_for([@skill, @skill.lessons.build]) do |f|
        .modal-body
          .form-group
            = f.label :signup, "Sign up"
            %p.help-block
              Tell #{@skill.user.first_name} a little about what you want to learn
            = text_area_tag :learning_request, nil, rows: 2, class: "form-control"
        .modal-footer
          = f.submit "Submit", class: "btn btn-custom"

- if @show_modal
  %script
    $(lessonModal).modal()

app/views/skills/_skill_short.html.haml
%a.block{:href=> skill_path(skill_short), :style=> "display:block"}
  .pin
    .skill-image
      = image_tag skill_short.picture
    .below-fold
      .profile-pic.circle-overlay
        = image_tag skill_short.user.picture
      .skill-short
        .teacher-name
          Taught by
          %span
            = skill_short.user.first_name
        .skill-title
          %span
            = skill_short.title

app/views/skills/index.html.haml
- provide(:title, "Lessons - LearnTo")


#skills

%hr.div-line

- if @network
  .logo
    = image_tag @network.logo
  - if not @events.empty?
    %h2.heading
      Upcoming Lessons at #{@network.name}
    .grid
      .row
        - @events.each do |event|
          .col-xs-12.col-sm-6.col-md-4
            = render partial: "events/event_short", locals: {event_short: event}
  %h2.heading Top lessons at #{@network.name}

  .grid
    .row
      - @network.skills.where("approved = ? AND hidden = ?", true, false).each do |skill|
        .col-xs-12.col-sm-6.col-md-4
          = render partial: "skills/skill_short", locals: {skill_short: skill}

  .new
    %p
      Can't find what you're looking to learn? Make a request   
      = link_to 'here', new_request_path
  / - if @network.id == 2
  %br
  #requests
  %h2.heading
    What you can teach at #{@network.name}

  %br
  .grid
    .row
      - @network.requests.each do |request|
        .col-xs-12.col-sm-6.col-md-4
          = render partial: "requests/request_short", locals: {request_short: request}
- else
  - if not @events.empty?
    %h2.heading
      Upcoming Lessons at MIT
    .grid
      .row
        - @events.each do |event|
          .col-xs-12.col-sm-6.col-md-4
            = render partial: "events/event_short", locals: {event_short: event}
  %h2.heading
    Public lessons at MIT
  .grid
    .row
      - @skills.each do |skill|
        .col-xs-12.col-sm-6.col-md-4
          = render partial: "skills/skill_short", locals: {skill_short: skill}


.new
  %p
    Can't find what you're looking to teach? Create a lesson    
    = link_to 'here', new_skill_path


- if current_user
  #aboutMeModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog
      .modal-content
        = form_for(@user) do |f|
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
            %h4#myModalLabel.modal-title Last step.  Tell us a little about yourself!
          .modal-body
            Fill out this information so others can know you better.  You can always edit this information by visiting your user profile.
            %hr.div-line
            .form-group
              = f.label :email
              %p.help-block
                We'll use this to send you an email when others contact you. No one can see it except for you.
              .input-group
                %span.input-group-addon @
                = f.text_field :email, class: "form-control"
            %hr.div-line
            .form-group
              = f.label :bio, "Biography"
              %p.help-block
                Tell others a little bit about yourself.  This makes them more likely to learn and teach with you.
              .input-group
                %span.input-group-addon
                  %span.glyphicon.glyphicon-user
                = f.text_area :bio, rows: 6, class: "form-control", placeholder: 'i.e. "I\'m a first year graduate student at MIT studying Mechanical Engineering.  I find teaching to be a great way of giving back, and meeting new people who are as passionate about learning as I am.  In my free time, I spend time hacking computer system (together and apart) and drink obscene amounts of coffee."'
            %hr.div-line
            .form-group
              = f.label :location, "Location"
              %p.help-block
                Where are you currently located?  It helps others find classes near them!
              .input-group
                %span.input-group-addon
                  %span.glyphicon.glyphicon-map-marker
                = f.text_field :location, class: "form-control", placeholder: "i.e. 'Cambridge, Massachusetts'"
            %hr.div-line
            .form-group
              = f.label :school, "School"
              %p.help-block
                Where do you, or have you gone to school?
              .input-group
                %span.input-group-addon
                  %span.glyphicon.glyphicon-book
                = f.text_field :school, class: "form-control", placeholder: "i.e. 'Massachusetts Institute of Technology'"
            %hr.div-line
            .form-group
              = f.label :work, "Work"
              %p.help-block
                Where do you, or have you worked?  Others find this information useful.
              .input-group
                %span.input-group-addon
                  %span.glyphicon.glyphicon-briefcase
                = f.text_field :work, class: "form-control", placeholder: "i.e. 'Google, J.P. Morgan'"
            %hr.div-line
            .form-group
              = f.label :network_ids, "Networks"
              %p.help-block
                Which networks are you apart of?  Don't worry if you don't see one, there are pleanty of public lessons.  If you want your group or organization listed here, #{mail_to "founders@learnto.com", "contact us"}.
              .input-group
                %span.input-group-addon
                  %span.glyphicon.glyphicon-cloud
                  -if @network
                    = f.select :network_ids, options_for_select([[@network.name, @network.id]], [@network.name, @network.id]), {}, :multiple => true, class: "form-control"
                  -else
                    = f.select :network_ids, Network.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, class: "form-control"
          .modal-footer
            = f.submit "Submit", class: "btn btn-custom"
            = link_to "Cancel", "#", class: "btn btn-custom", data: {dismiss: "modal"}


- if @show_user_bio
  %script
    $(aboutMeModal).modal()

app/views/skills/new.html.haml
- provide(:title, "New Lesson - LearnTo")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/skills/show.html.haml
- provide(:title, @skill.title + " - LearnTo")
- provide(:description, @skill.description)
= render 'skill'