config/routes.rb
Learnto::Application.routes.draw do

  get "networks/show"
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get 'auth/:provider/callback' => 'sessions#create', :as => "social_sign_in"
  get 'auth/failure' => redirect('/')

  get "healthbox" => "networks#show", defaults: {id: 5}
  get "bgsa" => "networks#show", defaults: {id: 2}
  get "startlabs" => "networks#show", defaults: {id: 3}
  get "startiap" => "networks#show", defaults: {id: 7}
  get "gsd" => "networks#show", defaults: {id: 8}
  get "cic" => "networks#show", defaults: {id: 9}
  get "sase" => "networks#show", defaults: {id: 10}

  get "about" => 'static_pages#about', :as => "about"
  get "guidelines" => 'static_pages#guidelines', :as => "guidelines"
  get "team" => 'static_pages#team', :as => "team"
  get "whyteach" => 'static_pages#whyteach', :as => "whyteach"

  get "registration/register", as: 'register'
  patch "registration/update", as: 'update_registration'


  get '/' => 'networks#show', :constraints => { :subdomain => /^(?!www).+/ }

  root 'skills#index'

  get 'networks/:id' => 'networks#show'
  get 'networks/:id/join' => 'networks#join', as: 'join_network'

  resources :users do
    collection do
      # get "requests"
    end
  end

  resources :reviews do
    member do 
    end
  end

  resources :requests do
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :requests do
    member do
      get "add_user"
    end
  end

  get "networks/:id" => "networks#show", :as => "network"
  
  resources :events do
    member do 
      post 'attend'
    end
  end

  resources :skills do
    collection do
      get 'networks'
    end
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :lessons do
    member do
      get "approve"
      get "ignore"
      get "complete"
      get "add_student"
    end
  end

  resources :conversations do
    collection do
      get "inbox"
      post "reply"
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  has_many :event_users
  has_many :students, :through => :event_users, :source => :user

  geocoded_by :address
  after_validation :geocode
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @return_to = request.path

    if current_user and session[:show_modal] and session[:event_id] == @event.id
      @show_modal = true
      session.delete(:show_modal)
    end

    if not current_user
      session[:show_modal] = true
      session[:event_id] = @event.id
    end
  end

  def new
    if not current_user
      redirect_to login_url(return_to: request.path)
      return
    end
    @event = Event.new
    @event.starts_at = 7.days.since(Time.now)
  end

  def create
    @event = current_user.events.new(event_params)

    if @event.save
      # TODO: Build event confirmation email
      Notifier.event_added(@event).deliver
      return redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Skill was successfully updated.'
    else
      render 'edit'
    end
  end

  def attend
    @event = Event.find(params[:id])
    if current_user
      if @event.students.include? current_user
        return redirect_to @event, notice: 'You are already signed up.'
      else
        @event.students << current_user
        if @event.capacity && (@event.students.count > @event.capacity)
          return redirect_to @event, notice: 'You have been added to the waitlist.'
        else
          Notifier.event_attend(current_user, @event).deliver
          return redirect_to @event, notice: 'You are successfully enrolled.'
        end
      end
    else
      return redirect_to @event, notice: 'You must be logged in to attend.'
    end
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :qualifications, :picture, :starts_at, :address, :capacity)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
.skill
  .row
    .col-md-7
      .box
        - if @event.approved == false
          .pending-approval
            Pending approval
        .row
          .col-md-12
            %h2.title
              = @event.title
        .row
          .col-md-6
            %a{href: user_path(@event.user), class: "circle-overlay"}
              = image_tag @event.user.picture
            %h4.instructor
              = link_to @event.user.name, user_path(@event.user)
        .row
          .col-md-6
            .social-share
              .facebook
                .fb-share-button{"data-href" => "#{request.original_url}", "data-type" => "button_count"}
              .twitter
                %a.twitter-share-button{"data-via" => "comelearnto", href: "https://twitter.com/share"} Tweet
          %hr.div-line
        .action-links
          - if current_user == @event.user
            = link_to 'Edit', edit_event_path(id: @event.id)
            / = link_to 'Remove', remove_skill_path(@event)
        - if not @event.description.empty?
          %h4 Description
          .description
            = simple_format(@event.description)
        - if not @event.qualifications.empty?
          %h4 Qualifications
          .description
            = simple_format(@event.qualifications)
        - if @event.approved
          - if current_user
            %button.btn.btn-custom.contact{"data-target" => "#eventModal", "data-toggle" => "modal"} Sign up!
          - else
            = link_to "Sign up or log in", login_path(return_to: @return_to), class: "btn btn-custom contact"


    .col-md-5
      .skill-image-full
        = image_tag @event.picture

      .box
        %h3 Lesson details
        .lesson-info
          .info-item
            %span.glyphicon.glyphicon-map-marker
            = @event.address
          .info-item
            %span.glyphicon.glyphicon-calendar
            = @event.starts_at
          - if @event.students.count > 0
            .info-item
              %span.glyphicon.glyphicon-user
              #{pluralize(@event.students.count, 'person')} attending 

#eventModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Lesson details
      .modal-body
        .lesson-info
          .info-item
            %span.glyphicon.glyphicon-map-marker
            = @event.address
          .info-item
            %span.glyphicon.glyphicon-calendar
            = @event.starts_at
      .modal-footer
        = link_to "Sign up", attend_event_path, method: 'post', class: "btn btn-custom"

- if @show_modal
  %script
    $(eventModal).modal()

app/views/events/_event_short.html.haml
%a.block{:href=> event_path(event_short), :style=> "display:block"}
  .pin
    .skill-image
      = image_tag event_short.picture
    .below-fold
      .profile-pic.circle-overlay
        = image_tag event_short.user.picture
      .skill-short
        .teacher-name
          Taught by
          %span
            = event_short.user.first_name
        .skill-title
          %span
            = event_short.title

app/views/events/_form.html.haml
%h3
  Teach on LearnTo
%p
  Teaching is a great way to meet new people with similar passions, become an expert in your field, and give back to your community. Fill out the following form and begin teaching soon!
%p
  Don't know when to teach?  Create a lesson and let others contact you to find a time #{link_to "here", new_skill_path}.
%hr.div-line
= form_for(@event, {role: "form"}) do |f|
  .form-group
    = f.label :title, "Learn to..."
    %p.help-block
      Choose and interesting title to capture people's attention.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-question-sign
      = f.text_field :title, class: "form-control", placeholder: "i.e. 'Cook Italian food' or 'Build a website'"
  %hr.div-line
  .form-group
    = f.label :description
    %p.help-block
      Describe what you're going to help others learn.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-globe
      = f.text_area :description, rows: 5, class: "form-control", placeholder: "i.e. I can help you learn to make basic pastas, sauces, and pizzas! We can even work on making Italian deserts such as gelato!"
  %hr.div-line
  .form-group
    = f.label :qualifications
    %p.help-block
      Tell others why you're able to teach them.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-ok
      = f.text_area :qualifications, rows: 5, class: "form-control", placeholder: "i.e. I've been cooking for myself for many years and learned how to cook from my Italian mother. I absolutely love cooking (mainly because I like eating!) and would love to help someone pick it up."
  %hr.div-line
  .form-group
    = f.label :starts_at, "When?"
    %p.help-block
      Only enter the date and time below if you have are scheduling this lesson for a specific time, otherwise people will be able to contact you to schedule a time and place to meet.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar
      = f.datetime_local_field :starts_at, class: "form-control"
  %hr.div-line
  .form-group
    = f.label :address, "Where?"
    %p.help-block
      Enter the address.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-map-marker
      = f.text_field :address, class: "form-control", placeholder: "i.e. '77 Massachusetts Avenue, Cambridge, MA'"
  %hr.div-line
  .form-group
    = f.label :capacity, "Capacity"
    %p.help-block
      Enter the capacity. Leave blank for no limit on the number of students.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-warning-sign
      = f.number_field :capacity, class: "form-control", placeholder: "i.e. '20'"
  %hr.div-line
  .form-group
    = f.label :image
    %p.help-block
      Pick an image that describes your lesson.
    .upload-event-picture.btn.btn-custom
      Pick image
    %br
    = f.hidden_field :picture, class: "form-control"
  %hr.div-line
    = f.submit "Submit", class: "btn btn-custom"

app/views/events/edit.html.haml
- provide(:title, "Edit Lesson - LearnTo")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/events/new.html.haml
- provide(:title, "New Scheduled Lesson - LearnTo")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/events/show.html.haml
- provide(:title, @event.title + " - LearnTo")
- provide(:description, @event.description)
= render 'event'