config/routes.rb
Learnto::Application.routes.draw do

  get "networks/show"
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get 'auth/:provider/callback' => 'sessions#create', :as => "social_sign_in"
  get 'auth/failure' => redirect('/')

  get "healthbox" => "networks#show", defaults: {id: 5}
  get "bgsa" => "networks#show", defaults: {id: 2}
  get "startlabs" => "networks#show", defaults: {id: 3}
  get "startiap" => "networks#show", defaults: {id: 7}
  get "gsd" => "networks#show", defaults: {id: 8}
  get "cic" => "networks#show", defaults: {id: 9}
  get "sase" => "networks#show", defaults: {id: 10}

  get "about" => 'static_pages#about', :as => "about"
  get "guidelines" => 'static_pages#guidelines', :as => "guidelines"
  get "team" => 'static_pages#team', :as => "team"
  get "whyteach" => 'static_pages#whyteach', :as => "whyteach"

  get "registration/register", as: 'register'
  patch "registration/update", as: 'update_registration'


  get '/' => 'networks#show', :constraints => { :subdomain => /^(?!www).+/ }

  root 'skills#index'

  get 'networks/:id' => 'networks#show'
  get 'networks/:id/join' => 'networks#join', as: 'join_network'

  resources :users do
    collection do
      # get "requests"
    end
  end

  resources :reviews do
    member do 
    end
  end

  resources :requests do
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :requests do
    member do
      get "add_user"
    end
  end

  get "networks/:id" => "networks#show", :as => "network"
  
  resources :events do
    member do 
      post 'attend'
    end
  end

  resources :skills do
    collection do
      get 'networks'
    end
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :lessons do
    member do
      get "approve"
      get "ignore"
      get "complete"
      get "add_student"
    end
  end

  resources :conversations do
    collection do
      get "inbox"
      post "reply"
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :picture, presence: true

  belongs_to :user
  has_many :request_users
  has_many :users, :through => :request_users
  has_many :lessons

  has_many :networks, :through => :user


  def hide
    self.hidden = true
    self.save!
  end

  def similar_requests
    if self.networks.size == 0
      return Request.where("approved = ? AND hidden = ? AND public = ?", true, false, true).order("RANDOM()").first(3)
    else
      return self.networks.first.requests.where("approved = ? AND hidden = ?", true, false).order("RANDOM()").first(3)
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @requests = Request.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @request = Request.find(params[:id])
    # @lesson = nil
    # if current_user
    #   @lesson = current_user.taken_class(@skill)
    #   if @lesson
    #     @review = current_user.reviewFor(@skill.user, @lesson)
    #   end
    # end
    # if !@review
    #   @review = Review.new
    # end

    if current_user and session[:show_modal] and session[:request_id] == @request.id
      @show_modal = true
      session.delete(:show_modal)
      session.delete(:request_id)
    end

    if not current_user
      session[:show_modal] = true
      session[:request_id] = @request.id
    end

    @return_to = request.path

    respond_to do |format|
      format.html
    end
  end

  def add_user
    @request = Request.find(params[:id])
    if current_user and !(@request.users.include? current_user)
      @request.users << current_user
      return redirect_to @request, notice: "Request added"
    end
    redirect_to @request
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      @request.users << current_user
      Notifier.request_added(@request).deliver
      redirect_to @request
    elsif @request.errors.any?
      # break
      @request.errors.full_messages.each do |msg|
        if !flash[:warning]
          flash[:warning] = msg + '. '
        else
          flash[:warning] += msg + '. '
        end
      end
      render 'new'
    else
      render 'new'
    end
  end

  def new
    if not current_user
      redirect_to login_url(return_to: request.path)
      return
    end
    @request = Request.new
  end

  def edit
    @request = current_user.requests.find(params[:id])
  end

  def remove
    @request = current_user.requests.find(params[:id])
    @request.hidden = true
    @request.save!
    flash[:warning] = "Request removed"
    redirect_to root_url
  end

  def update
    @request = current_user.requests.find(params[:id])
    if @request.update(request_params)
      redirect_to @request, notice: "Request was successfully updated"
    else
      render 'edit'
    end
  end

  private
    def request_params
      params.require(:request).permit(:title, :description, :picture, :public)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
%h3
  Request to learn on LearnTo
%p
  Always wanted to learn something? Make a request so that others around you can see it!

%hr.div-line
= form_for(@request, {role: "form"}) do |f|
  .form-group
    = f.label :title, "Learn to..."
    %p.help-block
      Choose an interesting title to capture people's attention.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-question-sign
      = f.text_field :title, class: "form-control", placeholder: "i.e. 'Cook Italian food' or 'Build a website'"
  %hr.div-line
  .form-group
    = f.label :description
    %p.help-block
      Describe what you want to learn and why.
    .input-group
      %span.input-group-addon
        %span.glyphicon.glyphicon-globe
      = f.text_area :description, rows: 5, class: "form-control", placeholder: "i.e. I want to learn how to make basic pastas, sauces, and pizzas! I've always wanted to get better at cooking and any help would be much appreciated!"
  %hr.div-line
  .form-group
    = f.label :image
    %p.help-block
      Pick an image that describes your request.
    .upload-request-picture.btn.btn-custom
      Upload an image that describes your request
    %br
    = f.hidden_field :picture, class: "form-control"
  %hr.div-line
  .form-group
    = f.label :public
    = f.check_box :public, {checked: false}
    %p.help-block
      Public requests are visible to anyone.  Private requests are visible to only those in your network.
  %hr.div-line
    = f.submit "Submit", class: "btn btn-custom"

app/views/requests/_request.html.haml
.request
  .row
    .col-md-7
      .box
        - if @request.approved == false
          .pending-approval
            Pending approval
        .row
          .col-md-12
            %h2.title
              = @request.title
        .row
          .col-md-6
            %a{href: user_path(@request.users.first), class: "circle-overlay"}
              = image_tag @request.users.first.picture
            %h4.instructor
              = link_to @request.users.first.name, user_path(@request.users.first)
        .row
          .col-md-6
            .social-share
              .facebook
                .fb-share-button{"data-href" => "#{request.original_url}", "data-type" => "button_count"}
              .twitter
                %a.twitter-share-button{"data-via" => "comelearnto", href: "https://twitter.com/share"} Tweet
          %hr.div-line
        .action-links
          - if current_user == @request.users.first
            = link_to 'Edit', edit_request_path(id: @request.id)
            = link_to 'Remove', remove_request_path(@request)
        %h4 Description
        .description
          = simple_format(@request.description)
        - if current_user
          %button.btn.btn-custom.contact{"data-target" => "#lessonModal", "data-toggle" => "modal"} Can you help #{@request.users.first.first_name} learn this? Contact to find a time and place!
        - else
          = link_to "Sign up or log in", login_path(return_to: @return_to), class: "btn btn-custom contact"

    .col-md-5
      .skill-image-full
        = image_tag @request.picture


#lessonModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Teach this lesson! 
      = form_for([@request, @request.lessons.build]) do |f|
        .modal-body
          .form-group
            = f.label :signup, "Sign up"
            %p.help-block
              Say how you can help and when/where you would like to meet.
            = text_area_tag :learning_request, nil, rows: 2, class: "form-control"
        .modal-footer
          = f.submit "Submit", class: "btn btn-custom"

- if @show_modal
  %script
    $(lessonModal).modal()

app/views/requests/_request_short.html.haml
.pin
  .skill-image
    %a.block{:href=> request_path(request_short), :style=> "display:block"}
      = image_tag request_short.picture
  .below-fold
    .profile-pic.circle-overlay
      = image_tag request_short.users.first.picture
    .skill-short
      .teacher-name
        Requested by
        %span
          = request_short.users.first.first_name
      .skill-title
        .row
          .col-md-9
            = link_to request_short.title, request_path(request_short)
          .col-md-1
            %span.glyphicon.glyphicon-arrow-up.arrow.clickable{link: add_user_request_url(request_short)}
          .col-md-1
            .badge.votes.neutral
              = request_short.users.size

app/views/requests/edit.html.haml
- provide(:title, "Edit Request - LearnTo")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/requests/index.html.haml
- provide(:title, "Requests - LearnTo")


#requests

- if @network
  %h2.heading Top requests at #{@network.name}
  .grid
    .row
      - @network.requests.where("approved = ? AND hidden = ?", true, false).each do |request|
        .col-xs-12.col-sm-6.col-md-4
          = render partial: "requests/request_short", locals: {request_short: request}
- else
  %h2.heading
    Open Lesson Requests
  .grid
    .row
      - @requests.each do |request|
        .col-xs-12.col-sm-6.col-md-4
          = render partial: "requests/request_short", locals: {request_short: request}

.new
  %p
    Want to teach something else? Sign up to teach  
    = link_to 'here', new_request_path

app/views/requests/new.html.haml
- provide(:title, "New Request - LearnTo")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/requests/show.html.haml
- provide(:title, @request.title + " - LearnTo")
- provide(:description, @request.description)
= render 'request'