config/routes.rb
Learnto::Application.routes.draw do

  get "networks/show"
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get 'auth/:provider/callback' => 'sessions#create', :as => "social_sign_in"
  get 'auth/failure' => redirect('/')

  get "healthbox" => "networks#show", defaults: {id: 5}
  get "bgsa" => "networks#show", defaults: {id: 2}
  get "startlabs" => "networks#show", defaults: {id: 3}
  get "startiap" => "networks#show", defaults: {id: 7}
  get "gsd" => "networks#show", defaults: {id: 8}
  get "cic" => "networks#show", defaults: {id: 9}
  get "sase" => "networks#show", defaults: {id: 10}

  get "about" => 'static_pages#about', :as => "about"
  get "guidelines" => 'static_pages#guidelines', :as => "guidelines"
  get "team" => 'static_pages#team', :as => "team"
  get "whyteach" => 'static_pages#whyteach', :as => "whyteach"

  get "registration/register", as: 'register'
  patch "registration/update", as: 'update_registration'


  get '/' => 'networks#show', :constraints => { :subdomain => /^(?!www).+/ }

  root 'skills#index'

  get 'networks/:id' => 'networks#show'
  get 'networks/:id/join' => 'networks#join', as: 'join_network'

  resources :users do
    collection do
      # get "requests"
    end
  end

  resources :reviews do
    member do 
    end
  end

  resources :requests do
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :requests do
    member do
      get "add_user"
    end
  end

  get "networks/:id" => "networks#show", :as => "network"
  
  resources :events do
    member do 
      post 'attend'
    end
  end

  resources :skills do
    collection do
      get 'networks'
    end
    resources :lessons
    member do
      get "remove"
    end
  end

  resources :lessons do
    member do
      get "approve"
      get "ignore"
      get "complete"
      get "add_student"
    end
  end

  resources :conversations do
    collection do
      get "inbox"
      post "reply"
    end
  end
end

app/views/layouts/_banner.html.haml
.banner
  = image_tag "dumplings.png", class: "banner-image image-responsive"
  .tagline
    %span.learnTo
      LearnTo 
    %span
    is a place to learn & share with others around you
  .how
    .row.up
      .col-xs-12.col-sm-6.col-md-4.step
        .Meet
          .banner-circle
            .text
              Meet
          .description
            Meet new people in your community
      .col-xs-12.col-sm-6.col-md-4.step
        .Learn
          .banner-circle
            .text
              Learn
          .description
            Learn something new in person
      .col-xs-12.col-sm-6.col-md-4.step
        .Share
          .banner-circle
            .text
              Share
          .description
            Give back by teaching something you love

app/views/layouts/_footer.html.haml
%footer.footer.navbar-static-bottom
  .container
    .row
      .col-md-4
        .logo
          = link_to (image_tag 'Learnto-logo-transparent.png', :class => 'footer-logo'), root_path
        .facebook
          = link_to (image_tag 'facebook-icon-32.png', :class => 'footer-social'), "https://www.facebook.com/pages/LearnTo/450840571693053", target:"_blank"
        .twitter
          = link_to (image_tag 'twitter-icon-32.png', :class => 'footer-social'), "https://twitter.com/comelearnto", target:"_blank"
      .col-md-4
        .links
          = link_to "Home", root_path
          = link_to "How it works", about_path
          = link_to "Team", team_path
          = mail_to "founders@learnto.com", "Contact"
      .col-md-4
        .copyright
          © 2013 LearnTo, Inc

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45056009-1', 'learnto.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.haml
 
%nav.navbar.navbar-custom.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      %button.nav-pills.navbar-toggle{"data-target" => "#collapse_links", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to (image_tag 'Learnto-logo-transparent.png', :class => 'nav-logo'), root_path
    #collapse_links.nav.navbar-collapse.collapse
      %ul.nav.nav-pills.navbar-left
        %li
          = link_to 'Teach', new_skill_path 
        %li
          = link_to 'Why Teach?', whyteach_path
      %ul.nav.nav-pills.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdownMenu1.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
              - if current_user.unread > 0
                = current_user.name + " (#{current_user.unread})"
              - else
                = current_user.name
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", role: "menu"}
              %li{role: "presentation"}
                = link_to user_path(current_user) do
                  %span.glyphicon.glyphicon-user
                  Your profile
              %li{role: "presentation"}
                = link_to inbox_conversations_path do
                  %span.glyphicon.glyphicon-envelope
                  Inbox (#{current_user.unread})
              %li.divider{role: "presentation"}
              - if current_user.networks.count > 0
                %li.dropdown-header{role: "presentation"} Your Networks
                - current_user.networks.each do |network|
                  %li{role: "presentation"}
                    = link_to network_path(network, anchor: "skills") do
                      %span.glyphicon.glyphicon-cloud
                      = network.name
                %li.divider{role: "presentation"}
              %li{role: "presentation"}
                = link_to logout_path do
                  %span.glyphicon.glyphicon-log-out
                  Logout
        - else
          %li
            = link_to "Login or Signup", login_path(return_to: request.original_url)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/_sidebar.html.haml
.side-nav
  .col-md-12.col-md-offset-2
    %ul
      %li
        = link_to "How It Works", about_path
      / %li
      /   = link_to "User guidelines", guidelines_path
      %li
        = link_to "Meet The Team", team_path
      %li
        = link_to "Why Teach?", whyteach_path

app/views/layouts/_static_banner.html.haml
.static-banner
  = image_tag "honey-banner.png", class: "static-banner-image"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "LearnTo"
    %meta{content: content_for?(:description) ? yield(:description) : "LearnTo", name: "description"}/
    = favicon_link_tag
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => false
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap-theme.min.css"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"
    = javascript_include_tag "//api.filepicker.io/v1/filepicker.js"
    = csrf_meta_tags
    = render 'layouts/shim'
  / .special-alert
  /   %br
  /   .row
  /     MIT Grad Students, teach someone on LearnTo and earn $10! Only valid for first 20 teachers.
  %body
    -flash.each do |name, msg| 
      = content_tag :div, msg, class: flash_class(name)
    .wrapper
      #header
        = render 'layouts/header' unless @disable_nav
        = render 'layouts/banner' if @show_banner
      #body.container
        = yield
        .push
    #footer
      = render 'layouts/footer' unless @disable_footer
    = render 'layouts/ga'
    .fb-root

app/views/layouts/static_pages.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "LearnTo"
    %meta{content: content_for?(:description) ? yield(:description) : "LearnTo", name: "description"}
    = favicon_link_tag
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => false

    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap-theme.min.css"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"

    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .wrapper.static
      #header
        = render 'layouts/header' unless @disable_nav
        = render 'layouts/static_banner'
      #body
        .row
          .col-md-3
            = render 'layouts/sidebar'
          .col-md-8
            = yield
        .push
    #footer
      = render 'layouts/footer' unless @disable_footer
    = render 'layouts/ga'